# Site settings
title: Cody Factory
description: About Cody Factory
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cody Zuschlag
user_description: Architecting and developing cloud first solutions.
user_title: Software Engineering and Cloud Architecture Consulting
email: cody@codyfactory.eu
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
